apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: "QlNWUElEanJabTNJZVJkRWdveWEzSTg5YTMxZ2cwMjh6UXFNQ3RnaGxDQmY3TkVWVU5JWEpRUUo5OUFMQUNZZUJqRlhKM3czQUFBQkFDT0dwMjA1"
# Note: The value of OPENAI_API_KEY must be Base64-encoded.
# You can encode it using the following command:
# echo -n "your-actual-api-key" | base64

